// src/components/legal/PrivacyPolicyModal.tsx

import React from 'react';
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  ModalFooter,
  Button,
  Text,
  Link,
  useColorModeValue,
  VStack,
  useToken,
} from '@chakra-ui/react';

interface PrivacyPolicyModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const PrivacyPolicyModal: React.FC<PrivacyPolicyModalProps> = ({ isOpen, onClose }) => {
  const [brand600, brand50] = useToken('colors', ['brand.600', 'brand.50']);
  const linkColor = useColorModeValue(brand600, 'blue.300');
  const hoverBg = useColorModeValue(brand50, 'whiteAlpha.200');

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="xl" isCentered motionPreset="scale">
      <ModalOverlay />
      <ModalContent mx={4} my={6} borderRadius="xl" boxShadow="lg">
        <ModalHeader fontSize="2xl" fontWeight="semibold" textAlign="center">
          Privacy Policy
        </ModalHeader>
        <ModalCloseButton />
        <ModalBody>
          <VStack align="start" spacing={4} fontSize="sm">
            <Text>
              <strong>Effective Date:</strong> January 1, 2024
            </Text>
            <Text>
              PF Geomatics is committed to protecting your privacy when you visit our website. Here’s how we handle your information:
            </Text>
            <Text>
              <strong>Information We Collect</strong><br />
              We do not collect any personal information directly from our visitors. We use Google Analytics to track sessions and analyse traffic on our site. This service collects data related to your device, browser, IP address, network location, and webpage interactions.
            </Text>
            <Text>
              <strong>Use of Cookies</strong><br />
              Google Analytics uses "cookies," which are small files placed on your device, to help analyse how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
            </Text>
            <Text>
              <strong>Data Protection</strong><br />
              We implement a variety of security measures to maintain the safety of your personal information when you visit our website.
            </Text>
            <Text>
              <strong>Third-party Links</strong><br />
              Our website may contain links to external sites that are not operated by us. We are not responsible for the content or privacy practices of these other sites.
            </Text>
            <Text>
              <strong>Your Consent</strong><br />
              By using our site, you consent to our website's privacy policy.
            </Text>
            <Text>
              If you have any questions regarding the privacy practices of PF Geomatics or your dealings with our website, please contact us at{' '}
              <Link
                href="mailto:info@pfgeomatics.co.uk"
                color={linkColor}
                _hover={{ textDecoration: 'underline', bg: hoverBg, px: 1, py: 0.5, borderRadius: 'md' }}
              >
                info@pfgeomatics.co.uk
              </Link>.
            </Text>
          </VStack>
        </ModalBody>
        <ModalFooter>
          <Button
            size="sm"
            variant="outline"
            borderColor={brand600}
            color={brand600}
            _hover={{ bg: hoverBg }}
            _active={{ bg: hoverBg, transform: 'scale(0.95)' }}
            onClick={onClose}
          >
            Close
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};

export default PrivacyPolicyModal;
